# Numpy Tutorial

In [1]:
#Importing Numpy package

import numpy as np


In [2]:
#Declaring simple array

a = np.array([2,3,4,6,2])
print(a)

[2 3 4 6 2]


In [3]:
#array shape parameter to get shape of the array
a.shape

(5,)

In [4]:
#Initiating static two dimensional array
b = np.array([[2,3,4,6,2],[4,5,6,9,4]])
print(b)

[[2 3 4 6 2]
 [4 5 6 9 4]]


In [5]:
b.shape

(2, 5)

In [6]:
#dtype parameter to get type of array
type(b)
b.dtype

dtype('int32')

In [8]:
# auto type casting to higher data types as Array is homogenous
c = np.array([2,3,4.2,6,2])
c

array([2. , 3. , 4.2, 6. , 2. ])

In [9]:
#Checking auto typeca--sting
c.dtype


dtype('float64')

In [15]:
#string can be auto typecasted as well.
b = np.array([6, 7, 8.0,'a'], dtype=int)
print(b)

ValueError: invalid literal for int() with base 10: 'a'

In [14]:
b.dtype

dtype('<U32')

In [16]:
#The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2.2], [3,4] ], dtype=float )
c

array([[1. , 2.2],
       [3. , 4. ]])

In [12]:
c.shape

(2, 2)

In [17]:
#The function zeros creates an array full of zeros
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
#arange function to create sequential array

data = np.arange(30)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
data.shape

(30,)

In [28]:
#reshape function to reshape array to the required dimension
data= data.reshape(6,5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [30]:
#more reshape examples
#data1 = np.arange(10,100,5).reshape(6,3)
data2 = np.arange(110,200,5).reshape(6,3)
data2

array([[110, 115, 120],
       [125, 130, 135],
       [140, 145, 150],
       [155, 160, 165],
       [170, 175, 180],
       [185, 190, 195]])

In [33]:
data3= np.arange(18).reshape(6,3)
data3**2
#data3

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]], dtype=int32)

In [38]:
#creating array for spliting examples
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
#horizontal splititing
a_hsplit = np.hsplit(a,2)
a_hsplit

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [42]:
#Vertical split
a_vsplit=np.vsplit(a,3)
a_vsplit

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
b

array(['6', '7', '8.0', 'a'], dtype='<U32')

In [44]:
#combing arrays with vertical stacking
np.vstack((a,b))

array([['0', '1', '2', '3'],
       ['4', '5', '6', '7'],
       ['8', '9', '10', '11'],
       ['12', '13', '14', '15'],
       ['16', '17', '18', '19'],
       ['20', '21', '22', '23'],
       ['6', '7', '8.0', 'a']], dtype='<U32')

In [46]:
#Numpy is capable of  huge Arrays manuplation very efficiently
a = np.arange(9000000).reshape(9000,1000)
a


array([[      0,       1,       2, ...,     997,     998,     999],
       [   1000,    1001,    1002, ...,    1997,    1998,    1999],
       [   2000,    2001,    2002, ...,    2997,    2998,    2999],
       ...,
       [8997000, 8997001, 8997002, ..., 8997997, 8997998, 8997999],
       [8998000, 8998001, 8998002, ..., 8998997, 8998998, 8998999],
       [8999000, 8999001, 8999002, ..., 8999997, 8999998, 8999999]])

In [51]:
#Generating random number with Numpy. random number are between 0 and 1
np.random.random()

0.7439600291182954

In [56]:
print("Random numbers with required shape")
print(np.random.rand(3,2))



#print("random integers between two numbers with required dsize")
#print(np.random.randint(10,50,10))

Random numbers with required shape
[[0.60319565 0.51059663]
 [0.84312085 0.49445777]
 [0.64475394 0.36632488]]


In [64]:
#Numpy floor, ceil and round

print(np.floor(5.9))
print(np.ceil(3.3))
print(np.round(4.4))


4.0
